name: autotaggin
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: "False"
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          fetch-depth: '2'

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.13' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/auto_tag/requirements.txt

      - name: execute py script # run sj-gobierno.py to get the latest data
        run: |
          echo $DRY_RUN
          python scripts/auto_tag/auto_tag.py
